//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDFutbol_MichaelTrujillo
{
    using System;
    using System.Collections.Generic;
    
    public partial class contratos
    {
        public int codcontrato { get; set; }
        public string coddnionie { get; set; }
        public Nullable<int> codEquipo { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<int> precioanual { get; set; }
        public Nullable<int> preciorecision { get; set; }
    
        public virtual equipos equipos { get; set; }
        public virtual futbolistas futbolistas { get; set; }
    }
}
