//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDFutbol_MichaelTrujillo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdFutbolEntities : DbContext
    {
        public bdFutbolEntities()
            : base("name=bdFutbolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contratos> contratos { get; set; }
        public virtual DbSet<equipos> equipos { get; set; }
        public virtual DbSet<futbolistas> futbolistas { get; set; }
        public virtual DbSet<ligas> ligas { get; set; }
    }
}
